language: python
python:
    - "2.7_with_system_site_packages"
    - "3.5"
    - "3.6"
before_install:
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7_with_system_site_packages ]]; then
          sudo apt-get update -qq;
          sudo apt-get build-dep -qq python-pygame;
          sudo apt-get install -qq python-pygame;
      fi
install:
    - pip install -r requirements.txt -r .travis_requirements.txt
script:
    - PYTHONPATH=./pool py.test --cov=.
after_success:
    - codeclimate-test-reporter
notifications:
    email: false
