language: python
python:
    - "3.5"
    - "3.6"
install:
    - pip install -r requirements.txt -r .travis_requirements.txt
script:
    - PYTHONPATH=./pool py.test --cov=.
after_success:
    - codeclimate-test-reporter
notifications:
    email: false
